[window]
width=1280
height=720
present_mode="vsync"
fps_max=144

[terrain]
set_seed=true
seed=1234
width=1000
height=1000

[terrain.perlin]
dots_per_cell=100

[terrain.simplex]
dots_per_cell=100

[terrain.wavelet]
frequency=0.014231234

[terrain.worley]
dots_per_cell=100
p=2.0
num_points=1

[terrain.dla]
num_steps=5
height_scale=0.15
fill=0.25
jiggle=0.021

[planet]
resolution=0
radius=100.0
compute_method="vulkan_compute"
perlin_cell_size=1.0
octaves=5
lacunarity=2.0
persistence=0.5
